//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraEquipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CabeceraEquipos()
        {
            this.DetalleEquipos = new HashSet<DetalleEquipos>();
        }
    
        public int id_cabecera { get; set; }
        public string nombre_cabecera { get; set; }
        public string descripcion_cabecera { get; set; }
        public bool estado_cabecera { get; set; }
        public System.DateTime creacion_cabecera { get; set; }
        public int usuario_cabecera { get; set; }
        public string terminal_cabecera { get; set; }
        public System.DateTime modificacion_cabecera { get; set; }
        public int usuariomod_cabecera { get; set; }
        public string terminalmod_cabecera { get; set; }
        public Nullable<int> aux1_cabecera { get; set; }
        public Nullable<int> aux2_cabecera { get; set; }
        public string aux3_cabecera { get; set; }
        public string aux4_cabecera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEquipos> DetalleEquipos { get; set; }
    }
}
