//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Equipos = new HashSet<Equipos>();
        }
    
        public int id_cliente { get; set; }
        public int provincia_cliente { get; set; }
        public int cuidad_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string ruc_cliente { get; set; }
        public string direccion_cliente { get; set; }
        public string telefono1_cliente { get; set; }
        public string telefono2_cliente { get; set; }
        public string email_cliente { get; set; }
        public string web_cliente { get; set; }
        public string contacto1_cliente { get; set; }
        public string celular1_cliente { get; set; }
        public string contacto2_cliente { get; set; }
        public string celular2_cliente { get; set; }
        public bool estado_cliente { get; set; }
        public Nullable<int> aux1_cliente { get; set; }
        public string aux2_cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipos> Equipos { get; set; }
    }
}
