//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipos()
        {
            this.OrdenesTrabajo = new HashSet<OrdenesTrabajo>();
        }
    
        public int id_equipo { get; set; }
        public int id_cliente { get; set; }
        public string grupo_equipo { get; set; }
        public string marca_quipo { get; set; }
        public string nombre_equipo { get; set; }
        public string modelo_equipo { get; set; }
        public string refrigeracion_equipo { get; set; }
        public string serie_equipo { get; set; }
        public string voltaje_equipo { get; set; }
        public string amperaje_equipo { get; set; }
        public string presion_equipo { get; set; }
        public Nullable<bool> estado_equipo { get; set; }
        public System.DateTime creacion_equipo { get; set; }
        public int usuario_equipo { get; set; }
        public string terminal_equipo { get; set; }
        public System.DateTime modificacion_equipo { get; set; }
        public int usuariomod_equipo { get; set; }
        public string terminalmod_equipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesTrabajo> OrdenesTrabajo { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
