//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesTrabajoDetalle
    {
        public int id_ordendetalle { get; set; }
        public int id_orden { get; set; }
        public int id_listatrabajo { get; set; }
        public string auxv_ordendetalle { get; set; }
        public Nullable<int> auxi_ordendetalle { get; set; }
    
        public virtual OrdenesTrabajo OrdenesTrabajo { get; set; }
    }
}
