//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int UserId { get; set; }
        public int PerfilId { get; set; }
        public string User_Name { get; set; }
        public string User_LastName { get; set; }
        public string User_Login { get; set; }
        public string User_Password { get; set; }
        public bool User_Estado { get; set; }
        public string User_ImagenPath { get; set; }
        public string User_Auxv1 { get; set; }
        public string User_Auxv2 { get; set; }
        public string User_Auxv3 { get; set; }
        public Nullable<int> User_Auxi1 { get; set; }
        public Nullable<int> User_Auxi2 { get; set; }
        public Nullable<int> User_Auxi3 { get; set; }
        public System.DateTime User_fechacreacion { get; set; }
    
        public virtual Tbl_Perfil Tbl_Perfil { get; set; }
    }
}
