//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Perfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Perfil()
        {
            this.Tbl_User = new HashSet<Tbl_User>();
        }
    
        public int PerfilId { get; set; }
        public string Perfil_Name { get; set; }
        public bool Perfil_Estado { get; set; }
        public string Perfil_Auxv1 { get; set; }
        public string Perfil_Auxv2 { get; set; }
        public string Perfil_Auxv3 { get; set; }
        public Nullable<int> Perfil_Auxi1 { get; set; }
        public Nullable<int> Perfil_Auxi2 { get; set; }
        public Nullable<int> Perfil_Auxi3 { get; set; }
        public System.DateTime Perfil_fechacreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_User> Tbl_User { get; set; }
    }
}
